ui: mocha-tdd
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
  - name: ie
    version: 8..latest
scripts:
  - "http://code.jquery.com/jquery-2.1.0.min.js"